# Generated by Django 3.1.4 on 2020-12-07 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Porridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='Название')),
                ('kkal', models.IntegerField(default=0, verbose_name='Калорийность')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('image', models.ImageField(upload_to='dish_shots/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Second_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='Название')),
                ('kkal', models.IntegerField(default=0, verbose_name='Калорийность')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('image', models.ImageField(upload_to='dish_shots/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='Название')),
                ('kkal', models.IntegerField(default=0, verbose_name='Калорийность')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('image', models.ImageField(upload_to='dish_shots/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Soup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=150, verbose_name='Название')),
                ('kkal', models.IntegerField(default=0, verbose_name='Калорийность')),
                ('ingredients', models.TextField(verbose_name='Состав')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('image', models.ImageField(upload_to='dish_shots/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('height', models.IntegerField(default=0, verbose_name='Рост')),
                ('weight', models.IntegerField(default=0, verbose_name='Вес')),
                ('kkal', models.IntegerField(default=0, verbose_name='Расход калорий')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
