# Generated by Django 3.1.4 on 2020-12-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clever_menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_of_week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота'), ('7', 'Воскресенье')], max_length=25, verbose_name='Day of week')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kkal_of_dish', models.IntegerField(max_length=100, verbose_name='Калорийность')),
                ('compose', models.TextField(verbose_name='Состав')),
                ('recipe', models.TextField(verbose_name='Рецепт')),
                ('kind_of_dish', models.CharField(max_length=100, verbose_name='Название')),
                ('img', models.ImageField(upload_to='gallery', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.DeleteModel(
            name='Porridge',
        ),
        migrations.DeleteModel(
            name='Second_course',
        ),
        migrations.DeleteModel(
            name='Snack',
        ),
        migrations.DeleteModel(
            name='Soup',
        ),
        migrations.AddField(
            model_name='profile',
            name='kkal_limit_var',
            field=models.CharField(default=1, max_length=100, verbose_name='Вариант программы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day_of_week',
            name='dishes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clever_menu.dishes'),
        ),
    ]
