# Generated by Django 3.1.4 on 2020-12-24 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clever_menu', '0003_auto_20201224_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='day_of_week',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='clever_menu.profile'),
            preserve_default=False,
        ),
    ]
