# Generated by Django 3.1.4 on 2020-12-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clever_menu', '0004_day_of_week_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_of_week',
            name='dishes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='clever_menu.dishes'),
        ),
    ]
