# Generated by Django 3.1.4 on 2020-12-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clever_menu', '0005_auto_20201224_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_of_week',
            name='dishes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='clever_menu.dishes'),
        ),
    ]
