# Generated by Django 3.1.4 on 2020-12-24 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clever_menu', '0006_auto_20201224_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_of_week',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dishes',
            name='days',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes_day', to='clever_menu.day_of_week'),
            preserve_default=False,
        ),
    ]
