# Generated by Django 3.1.4 on 2020-12-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clever_menu', '0008_auto_20201224_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='days',
        ),
        migrations.AddField(
            model_name='day_of_week',
            name='dishes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes_days', to='clever_menu.dishes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day_of_week',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_days', to='clever_menu.profile'),
        ),
    ]
