# Generated by Django 3.1.5 on 2021-01-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clever_menu', '0014_auto_20210117_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_of_week',
            name='dishes',
        ),
        migrations.AddField(
            model_name='day_of_week',
            name='dishes',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='clever_menu.dishes'),
        ),
    ]
