# Generated by Django 3.1.5 on 2021-01-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clever_menu', '0015_auto_20210117_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day_of_week',
            name='dishes',
        ),
    ]
